In [ ]:
# src: https://www.youtube.com/watch?v=ZB7BZMhfPgk
# Introduction to numerical computing with numpy 

In [3]:
# python add 2 arrays
a = [1,2,3,4]
b = [5,6,7,8]
a+b   # this is concatenate, not pair-wise addition

[1, 2, 3, 4, 5, 6, 7, 8]

In [8]:
result = []
for first, second in zip(a, b):
    result.append(first +second)
result     # this is pair-wise addition, what we expected

# this is what numpy can help 


[6, 8, 10, 12]

In [21]:
# intro of np array
import numpy as np   # np prefix 

a = np.array([1,2,3,4])
type(a)
# numpy.ndarray, nd = n-dimensional, int64 : 64bit int

numpy.ndarray

In [22]:
a.dtype  # enforce data type

dtype('int64')

In [23]:
f = np.array([1.1, 2.2, 3.3])
f.dtype   # float64 : floating type

dtype('float64')

In [24]:
# access array value
a[0]

1

In [25]:
# assign array value
a[0]=10
a[0]

10

In [27]:
# assign float to int array, floating point is truncated
a[0]= 10.5
a   # [10,  2,  3,  4], .5 is truncated


array([10,  2,  3,  4])

In [26]:
# check array value changed 
a

array([10,  2,  3,  4])

In [28]:
# few ndarray features 
a.ndim   # number of dimennsions 

1

In [29]:
# shape, possibly the most important one , always a tuple 
# show number of elements in each dimensions, 2d has 2 element, 3d has 3 elements
# here shape is similar to matplot.shape

a.shape

(4,)

In [30]:
# shape is different from size, which is the number of the element 
a.size

4

In [33]:
# how can we do with np array, do element wise operation, they are not matrix
a = np.array([1,2,3,4])
f = np.array([1.1, 2.2, 3.3, 4.4])
a + f  # pair wise addition
print(a+f, a-f, a*f, a/f)

[2.1 4.2 6.3 8.4] [-0.1 -0.2 -0.3 -0.4] [ 1.1  4.4  9.9 17.6] [0.90909091 0.90909091 0.90909091 0.90909091]


In [35]:
# vectorization, using single statement without loop 
f ** a

array([  1.1   ,   4.84  ,  35.937 , 374.8096])

In [36]:
# multiple by constant, apply to all elelemnt 
a * 10

array([10, 20, 30, 40])

In [38]:
# tools, called Universal Functions (ufuncs), math functions
# for each element in the array
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [39]:
# np.array is a list, mutable, can assign values , enforce data types by casting


In [42]:
# multi-dimensional arrays, list of lists
a = np.array([[0,1,2,3], [4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [46]:
# shape = (row, columns)
a.shape

(2, 4)

In [47]:
# number of dimensions
a.ndim

2

In [48]:
# total element count
a.size

8

In [51]:
# get / set elements , python uses 0-based indexing
a[1,3] = 10   # [row, column]
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 10]])

In [52]:
# single index to get elements of that dimension
a[1]   # 2nd row

array([ 4,  5,  6, 10])

In [59]:
# numpy indexing and slicing 
# slicing, var[lower:upper:step]
a = [1,2,3,4,5]
a[1:3]  # [2, 3]
a[1:-2]  # negative indices work also
a[-4:3]  # [2, 3]

# omit indices, assumed to be the beginning or end of the list 
a[:3]   # [1, 2, 3]
a[-2:]   # [4, 5], grab last 2 elements
a[::2]   # every other element

[1, 3, 5]

In [102]:
# array slicing, apply to row and elements 
a = np.array([[1,2,3,4], [5,6,7,8], [10,11,12,13], [20,21,22,23]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [106]:
# first row, 1-3 elements
a[0, 1:3]   # [2, 3]
a[2:, 2:]   # [[6, 7, 8], throw away 2 rows, 2 columns
# every row, column number 2
a[:, 2]     # [ 3,  7, 12, 22], column selection, lonly colon: everything in that dimension
a[2::2, ::2]    # row to the end every other, column from beginning till 2nd from end

array([[10, 12]])

In [109]:
# create an array 
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [111]:
# a[:,::]   # 2d needs a comma, and :: for slicing
a[:, 1::2]  # start from 2nd column, every other column

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [112]:
a[4, :]  # row number 4 and every elements

array([20, 21, 22, 23, 24])

In [113]:
a[-1, :]   # -1 means last row, the oldest, newest data; 4 means the fifth row 

array([20, 21, 22, 23, 24])

In [119]:
a[1::2,:3:2]   # every other rows, from beginning to 3rd column, every other elements

array([[ 5,  7],
       [15, 17]])

In [125]:
# attention, slicing array uses same underline array, changes are reflected in original array 
# both correct and incorrect, helps memory sharing/efficiency and mutable arrays surprises
a = np.array([1,2,3,4])
b = a[:2]
b[0] = -1
b,a    # (array([-1,  2]), array([-1,  2,  3,  4])) , both changed

(array([-1,  2]), array([-1,  2,  3,  4]))

In [130]:
b = a.copy()  # this allocate a new diff memory buffer
a, b
b[0] = 10
a,b  # (array([-1,  2,  3,  4]), array([10,  2,  3,  4]))

(array([-1,  2,  3,  4]), array([10,  2,  3,  4]))

In [3]:
# slices are references 
# slices are references to locations in memory
# these memory locations can be used in assignment operations 
import numpy as np
a = np.array([0,1,2,3,4,5])
a[-2:]   # slicing last 2 elements 
a[-2:] = [-1, -2]   # insert an iterable of length two 
a[-2:] = 99  # array([ 0,  1,  2,  3, 99, 99]), assign scalar value
a

array([ 0,  1,  2,  3, 99, 99])

In [4]:
# what does [] and () in python do
# a[0]  , syntactic sugar, for a call to __getitem__(0), to get value of index of 0
# a[0]=10, for a call to __setitem__(0, 10), [] translates to assignment call
# a = np.array([1,2,3]), () is call a function, make np.array.__call__([1,2,3])
# Dunder methods, special methods, python data model
# Fluent Python, a good intermediate book about python 

In [ ]:
# Fancy indexing (masking, boolean indexing, logical indexing)
# indexing by value

In [12]:
# indexing by position
a = np.arange(0, 80, 10)
a
indices = [1, 2, -3]
y = a[indices]
a[indices] = 99   # array([ 0, 99, 99, 30, 40, 99, 60, 70])
a

array([ 0, 99, 99, 30, 40, 99, 60, 70])

In [19]:
# indexing with booleans
a = np.arange(0, 80, 10)  # array([ 0, 10, 20, 30, 40, 50, 60, 70])
len(a)
mask = np.array([0, 1, 1, 0, 0, 0, 1, 0], dtype=bool)
len(mask)
y = a[mask]   # array([10, 20, 60])
y

array([10, 20, 60])

In [29]:
# threshold data 
a = np.array([-1, -3, 1, 4, -6, 9, 3])
a < 0  # array([ True,  True, False, False,  True, False, False])
negative = a < 0
# get values based on values 
a[negative]  # array([-1, -3, -6])
# replace negative values with 0
a[negative] = 0  # array([0, 0, 1, 4, 0, 9, 3])
# replace negative values with 0


array([0, 0, 1, 4, 0, 9, 3])

In [59]:
# Fancy indexing in 2D 
a = np.arange(25).reshape(5, 5)
'''
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])
'''
a[[0], [2]]  # array([2])
a[[0,2], [2,3]]  # array([ 2, 13])
a[[0,2,3], [2,3,1]]  #array([ 2, 13, 16]), [[rows], [cols]]
a[[0,2,3,3], [2,3,1,-1]]   # array([ 2, 13, 16, 19])

array([ 2, 13, 16, 19])

In [61]:
# modular operation
a % 3 # all numbers are divided by 3

array([[0, 1, 2, 0, 1],
       [2, 0, 1, 2, 0],
       [1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1],
       [2, 0, 1, 2, 0]])

In [63]:
a[a % 3]  # convert to 3-d arrays, not what we want

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [ 0,  1,  2,  3,  4]],

       [[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [ 0,  1,  2,  3,  4]]])

In [66]:
a % 3 == 0  # a mask 
a[a % 3 ==0]  # numbers divided by 3 with 0, array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [ ]:
# multi-dimensional arrays 
# numpy uses row major, preserves rows number, prepand dimensions
'''
(4,) - 1 row, 4 columns
(2, 4) - 2 rows, 4 columns 
(3, 2, 4) - 3 depth, 2 rows, 4 columns
(2, 3, 2, 4) - 2 arrays, of, 3 depth, 2 rows, 4 columns
'''

In [69]:
# array calculation methods 
'''
rules
1, shape match 
2, (+-*/exp,log,...) apply element by element, on the values 
3, reduction operations (mean, std, skew, kurt, sum, prod...) apply to the whole array, unless an axis is specified
4, missing values propagate unless explicitly ignored (nanmean, nansum)
'''
np.nan  # nan
np.nan + 1   # nan

nan

In [77]:
# array broadcasting - element by element
# prepend ones to smaller array's shape
import numpy as np 
a = np.ones((3,5))   # a.shape == (3,5)
b = np.ones((5,))    # b.shape = [5,]
b.reshape(1,5)    # result is a (1,5)-shaped array
b[np.newaxis, :]   # equivlent, more concise

array([[1., 1., 1., 1., 1.]])

In [79]:
# dimensions of size 1 are repeated without copying
c = a + b  # c.shape == (3,5)
# 3 is logically equivalent to ...
tmp_b = b.reshape(1,5)
tmp_b_repeat = tmp_b.repeat(3, axis=0)
c = a + tmp_b_repeat
# but broadcasting makes no copies of "b"s data!

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [33]:
import numpy as np
a = np.array([[1,2,3,4,5], [6,7,8,9,10]])
# adding up all the values in an array 
a.sum()

55

In [37]:
# sum along 0th axis
a.sum(axis=0)

array([ 7,  9, 11, 13, 15])

In [46]:
# sum along last axis, sum of array element, [1,2,3,4,5] = 15, [6,7,8,9,10] = 40
# -1 is row wise 
# -2 is column wise `
a.sum(axis=-1)

array([15, 40])

In [47]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [48]:
# sum of pair-wise of rows
a.sum(axis=-2)

array([ 7,  9, 11, 13, 15])

In [50]:
# ((5,6)) - has to be tuple 
a = np.ones((5,6))
a

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [51]:
# check array shape, to help understand how sum works
a.shape

(5, 6)

In [55]:
# this tells how the result shape looks like, it will be six values
a.sum(axis=0).shape

(6,)

In [56]:
# this tells sum by rows
a.sum(axis=-1).shape

(5,)

In [63]:
# min/max 
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
# reducer 
np.min(a)

1

In [64]:
# max value for one dimension
a.max(axis=0)

array([4, 5, 6])

In [65]:
a.max(axis=-1)

array([3, 6])

In [66]:
# the location of a max, not the value
a.argmax()

5

In [67]:
# the location of the min, 
a.argmin()

0

In [69]:
# unravel  un-flatten 1D location of max
np.unravel_index(a.argmax(), a.shape)

(1, 2)

In [70]:
# where function 
a = np.array([1,2,3,4,5,5])
a

array([1, 2, 3, 4, 5, 5])

In [71]:
# get a mask
a == a.max()

array([False, False, False, False,  True,  True])

In [73]:
# find the location of max values
np.where(a==a.max())

(array([4, 5]),)

In [76]:
np.where(a > 3)

(array([3, 4, 5]),)

In [205]:
# create a 2d 10x12 array
a=np.arange(120, dtype=int).reshape(10,12)
a

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47],
       [ 48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71],
       [ 72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83],
       [ 84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107],
       [108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119]])

In [206]:
# save data on disk
np.savetxt('data.csv', a, delimiter=',', fmt='%d')
!ls -l

total 184
-rw-r--r--  1 user  staff    370 30 Mar 23:06 data.csv
-rw-r--r--  1 user  staff    370 30 Mar 22:45 data.txt
-rw-r--r--  1 user  staff   1088 30 Mar 22:16 data.txt.npy
-rw-r--r--  1 user  staff  24857 30 Mar 04:51 dolly-lora-gpt-j-6b.ipynb
-rw-r--r--  1 user  staff  50115 30 Mar 23:04 numpy-tutoial.ipynb


In [210]:
# set display options
np.set_printoptions(threshold=100)
# load file 
from numpy import loadtxt

np.fromstring(x, dtype=int, sep=',')

conv = lambda x: np.fromstring(x, dtype=int, sep=',')
data = np.genfromtxt('data.csv', dtype=float, delimiter=',')  #loadtxt('data.csv')
data, data.shape


(array([[  0.,   1.,   2., ...,   9.,  10.,  11.],
        [ 12.,  13.,  14., ...,  21.,  22.,  23.],
        [ 24.,  25.,  26., ...,  33.,  34.,  35.],
        ...,
        [ 84.,  85.,  86., ...,  93.,  94.,  95.],
        [ 96.,  97.,  98., ..., 105., 106., 107.],
        [108., 109., 110., ..., 117., 118., 119.]]),
 (10, 12))

In [214]:
# show first 5 rows
data[:5]

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35.],
       [36., 37., 38., 39., 40., 41., 42., 43., 44., 45., 46., 47.],
       [48., 49., 50., 51., 52., 53., 54., 55., 56., 57., 58., 59.]])

In [217]:
# show first 3 columns
first_two_cols = data[:, :3]
first_two_cols

array([[  0.,   1.,   2.],
       [ 12.,  13.,  14.],
       [ 24.,  25.,  26.],
       [ 36.,  37.,  38.],
       [ 48.,  49.,  50.],
       [ 60.,  61.,  62.],
       [ 72.,  73.,  74.],
       [ 84.,  85.,  86.],
       [ 96.,  97.,  98.],
       [108., 109., 110.]])

In [220]:
# show every row, from column 3
data[:, 3:]

array([[  3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.],
       [ 15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,  23.],
       [ 27.,  28.,  29.,  30.,  31.,  32.,  33.,  34.,  35.],
       [ 39.,  40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.],
       [ 51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.],
       [ 63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,  71.],
       [ 75.,  76.,  77.,  78.,  79.,  80.,  81.,  82.,  83.],
       [ 87.,  88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.],
       [ 99., 100., 101., 102., 103., 104., 105., 106., 107.],
       [111., 112., 113., 114., 115., 116., 117., 118., 119.]])

In [224]:
# show min, max, mean, std values 
data.min(), data.max(), data.mean(), data.std()

(0.0, 119.0, 59.5, 34.63981331743384)

In [228]:
# calculate based on locations
# check shape to see how many values do we expect  
data.min(axis=-1).shape

(10,)

In [234]:
# min by columns
data.min(axis=0)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [235]:
# max by rows
data.max(axis=1)

array([ 11.,  23.,  35.,  47.,  59.,  71.,  83.,  95., 107., 119.])

In [252]:
# get indices of max values
data.argmax(axis=1)

array([11, 11, 11, 11, 11, 11, 11, 11, 11, 11])

In [253]:
# get indices of min values
data.argmin(axis=1)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [255]:
# find the location of max value 
np.where(data == data.max())

(array([9]), array([11]))

In [259]:
# unravel index to get same value
data.argmax(), np.unravel_index(data.argmax(), data.shape)

(119, (9, 11))

In [262]:
# collect the row max data all in one array
data.max(axis=1)

array([ 11.,  23.,  35.,  47.,  59.,  71.,  83.,  95., 107., 119.])

In [264]:
# find row which has the max value 
data.max(axis=1).argmax()

9

In [275]:
# get column 1 for all rows whose value is 1,. get mask
subdata = data[:, 1] == 1
subdata

array([ True, False, False, False, False, False, False, False, False,
       False])

In [276]:
# get average based of subdata mask
data[subdata].mean(axis=0)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [ ]:
'''
how numpy array is represented in memory 

memory block: _1, _2, _3, _4, _5, ...    # one long array

dtype: * (int64, data type)
ndim: 2 
shape: 3, 3
strides: 24, 8  (memory offset)
data: data 

for a.T  , transpose, not trigger memory copy 
shape: 3,2
stride, 8, 24


python view: 

0 1 2 
3 4 5 
6 7 8 


'''

In [277]:
'''
Operations on the array structure
Operations that only affect the array structue, not the data
can usually be executed without copying memory
'''

a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [278]:
# reshape not a new copy of data, the original data does not get reordered.
b = a.reshape(2,3)
b  # 3 columns, 2 rows


array([[0, 1, 2],
       [3, 4, 5]])

In [279]:
# transpose swaps the order of axes 
a = np.array([[0,1,2], [3,4,5]])
a.shape

(2, 3)

In [280]:
# transpose, two columns, 3 rows 
a.T, a.T.shape

(array([[0, 3],
        [1, 4],
        [2, 5]]),
 (3, 2))

In [283]:
# transpose does not mvoe values around memory, it changes "order" in the array 
# transpose is a very low cost operation 
a.strides, a.T.strides


((24, 8), (8, 24))

In [284]:
# reshape, shape
a=np.array([[0,1,2], [3,4,5]])
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [285]:
# shape 
a = np.arange(6)
a, a.shape

(array([0, 1, 2, 3, 4, 5]), (6,))

In [287]:
# reshape array in place to 2x3
a.shape = (2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [288]:
# turn ndarray to 1d array, flattten (safe), ravel(efficient)
# flatten convert multi-dimensional array into a 1d array
# the new array is a copy of the original data 
a = np.array([[0,1], [2,3]])
b = a.flatten()
b

array([0, 1, 2, 3])

In [289]:
# change b does not change a 
b[0]=10
b

array([10,  1,  2,  3])

In [290]:
# ravel is the same as flatten, but returnsa reference (view) of array if possible
# otherwise teh new array copies the data 
b = a.ravel()
b

array([0, 1, 2, 3])

In [291]:
# change b does change a , ***
b[0] = 10
b, a

(array([10,  1,  2,  3]),
 array([[10,  1],
        [ 2,  3]]))